name: Vulnerability Scan Daily
on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build and scan image
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: newrelic/infrastructure-bundle
      DOCKER_IMAGE_TAG: ci
      TRIVY_DISABLE_VEX_NOTICE: "true"
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Download integrations
        run: go run downloader.go

      - name: Build and load docker image
        run: |
          DOCKER_PLATFORMS=linux/amd64 ./docker-build.sh . --load

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.29.0
        id: trivy
        with:
          image-ref: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_IMAGE_TAG }}
          # We use a custom template to keep the text small
          format: 'template'
          template: |
            {{- range . }}
            Target: {{ .Target }}
            {{- if (eq (len .Vulnerabilities) 0) }}
            No vulnerabilities found.
            {{- else }}
            | ID | Severity | Library | Fixed In |
            |----|----------|---------|----------|
            {{- range .Vulnerabilities }}
            | {{ .VulnerabilityID }} | {{ .Severity }} | {{ .PkgName }} | {{ .FixedVersion }} |
            {{- end }}
            {{- end }}
            {{ end }}
          exit-code: 0 
          ignore-unfixed: true 
          severity: "CRITICAL,HIGH"
          output: "raw-report.txt"

      - name: Format Slack Message
        id: format_message
        run: |
          # 1. Check if the report contains a CVE
          if grep -q "CVE-" raw-report.txt; then
             # Clean up empty lines and get the content
             REPORT_CONTENT=$(cat raw-report.txt | sed '/^[[:space:]]*$/d' | head -c 3500)
             MSG="*ðŸš¨ Security Scan Issues Found*\nVulnerabilities detected in \`${{ env.DOCKER_IMAGE }}\`:\n\`\`\`\n$REPORT_CONTENT\n\`\`\`"
          else
             MSG="*âœ… Security Scan Passed*\nNo High or Critical vulnerabilities found for \`${{ env.DOCKER_IMAGE }}\`."
          fi
          
          echo "SLACK_MESSAGE<<EOF" >> $GITHUB_OUTPUT
          echo -e "$MSG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Slack notification
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.COREINT_SLACK_TOKEN }}
          slack-channel: ${{ secrets.TEST_SLACK_CHANNEL }}
          slack-text: ${{ steps.format_message.outputs.SLACK_MESSAGE }}
          slack-optional-parse: full